# Generated by Django 5.0.12 on 2025-12-16 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_apellido", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("asunto", models.CharField(max_length=50)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
