# Generated by Django 5.0.12 on 2025-12-16 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("subtitulo", models.CharField(blank=True, max_length=200, null=True)),
                ("pie_pagina", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha", models.DateTimeField(auto_now=True)),
                ("texto", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="static/post_default.png",
                        null=True,
                        upload_to="media",
                    ),
                ),
                ("publicado", models.DateField(default=django.utils.timezone.now)),
                (
                    "categoria",
                    models.ForeignKey(
                        default="Sin categoria",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posts.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ("-publicado",),
            },
        ),
    ]
