# Generated by Django 5.0.12 on 2025-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_categoria_nombre_alter_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pie_pagina',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
