# Generated by Django 5.0.12 on 2025-12-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_pie_pagina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pie_pagina',
            new_name='pie_foto',
        ),
    ]
